spring.application.name=pago-serv
spring.datasource.url=jdbc:postgresql://localhost:5432/pago-serv
spring.datasource.username=postgres
spring.datasource.password=linux
spring.cloud.config.enabled=false

# Configuración de GestoPago
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678

# Configuración de Timeouts para Feign Client
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000